extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "../target/debug/ssa_construction",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "../target/debug/ssa_construction",
    "brili -p {args}",
]
